const FETCH_FEATURED_PRODUCTS_IS_LOADING = 'FETCH_FEATURED_IS_LOADING';
const FETCH_FEATURED_PRODUCTS_SUCCESS = 'FETCH_FEATURED_PRODUCTS_SUCCESS';
const FETCH_FEATURED_PRODUCTS_FAILURE = 'FETCH_FEATURED_PRODUCTS_FAILURE';

export {
  FETCH_FEATURED_PRODUCTS_IS_LOADING,
  FETCH_FEATURED_PRODUCTS_SUCCESS,
  FETCH_FEATURED_PRODUCTS_FAILURE,
};
