const FETCH_NEW_PRODUCT_IS_LOADING = 'FETCH_NEW_PRODUCT_IS_LOADING';
const FETCH_NEW_PRODUCT_SUCCESS = 'FETCH_NEW_PRODUCT_SUCCESS';
const FETCH_NEW_PRODUCT_FAILURE = 'FETCH_NEW_PRODUCT_FAILURE';

export {
  FETCH_NEW_PRODUCT_IS_LOADING,
  FETCH_NEW_PRODUCT_SUCCESS,
  FETCH_NEW_PRODUCT_FAILURE,
};
