const FETCH_PRODUCT_CARD_LIST_IS_LOADING = 'FETCH_NEW_PRODUCT_IS_LOADING';
const FETCH_PRODUCT_CARD_LIST_SUCCESS = 'FETCH_NEW_PRODUCT_SUCCESS';
const FETCH_PRODUCT_CARD_LIST_FAILURE = 'FETCH_NEW_PRODUCT_FAILURE';

export {
  FETCH_PRODUCT_CARD_LIST_IS_LOADING,
  FETCH_PRODUCT_CARD_LIST_SUCCESS,
  FETCH_PRODUCT_CARD_LIST_FAILURE,
};
